name: CI Improved
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["apps/web", "apps/api", "packages/shared"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.15.5 --activate
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run tests for package
        run: pnpm --filter "${{ matrix.package }}" run test -- --threads=1 --reporter=dot
