name: ci-web

on:
  push:
    paths:
      - 'apps/web/**'
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
        working-directory: apps/web
      - name: Lint
        run: npm run lint
        working-directory: apps/web
      - name: Test coverage
        run: npm run test:coverage
        working-directory: apps/web
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./apps/web/coverage
          flags: web
          name: web-coverage
          fail_ci_if_error: false
      - name: Build
        run: npm run build
        working-directory: apps/web
