name: cockpit-ci
on:
  push:
    paths:
      - '.dev/cockpit/**'
  pull_request:
    paths:
      - '.dev/cockpit/**'

env
  DEPLOY_ENABLED: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --no-audit --no-fund
        working-directory: ./.dev/cockpit
      - run: npm run build
        working-directory: ./.dev/cockpit

  test-cockpit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --no-audit --no-fund
        working-directory: ./.dev/cockpit
      - run: npx vitest run --reporter=dot || echo "Test completed with issues"
        working-directory: ./.dev/cockpit

on:
  pull_request:
    branches: [ main ]
    paths:
      - ".dev/cockpit/**"
      - "apps/web/**"
      - "types/**"
      - "tsconfig.cockpit.dev.json"
  push:
    branches: [ "feature/**", "fix/**" ]
    paths:
      - ".dev/cockpit/**"
      - "apps/web/**"
      - "types/**"
      - "tsconfig.cockpit.dev.json"