name: Coverage Check
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - ".github/**"

jobs:
  test-and-collect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["apps/web", "apps/api"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.15.5 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests for ${{ matrix.package }}
        run: |
          pnpm --filter "${{ matrix.package }}" run test -- --coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.package }}
          path: |
            ${{ matrix.package }}/coverage

  aggregate:
    runs-on: ubuntu-latest
    needs: test-and-collect
    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/coverage
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Aggregate coverage and comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_THRESHOLD: "85"
          COVERAGE_MODE: "diff"
        run: node scripts/aggregate_coverage_and_comment.js
