name: Deploy WEB to Azure
on:
  push:
    branches: ["main", "fix/**", "release/**"]
  workflow_dispatch: {}
env:
  AZURE_APP_NAME: "econeura-web-dev"
  VITE_AI_ENDPOINT: "https://econeura-api-dev.azurewebsites.net/api/ai"
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: VITE_AI_ENDPOINT="${{ env.VITE_AI_ENDPOINT }}" npm run build
      - run: node -e "require('fs').cpSync('server.js','dist/server.js')"
      - name: Sanity dist
        run: |
          [ -f dist/index.html ] && [ -f dist/server.js ] || (echo dist incompleto; exit 2)
      - run: cd dist && zip -r ../web-artifact.zip .
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: web-artifact.zip
