name: Deploy WEB to Azure App Service
on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-web.yml"
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: apps/web } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "pnpm" }
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.5 --activate
      - run: pnpm install --frozen-lockfile
      - name: Build (Vite)
        run: |
          pnpm run build
          test -d dist && test -f dist/index.html || (echo "dist incompleto" && exit 2)
      - name: Copy server.js into dist (SSR static server)
        run: |
          if [ -f server.js ]; then
            cp server.js dist/server.js
            echo "✅ server.js copied"
          else
            echo "WARN: server.js not found, skipping"
          fi
      - name: Validate artifact contents
        run: |
          ls -la dist | head -20
          test -f dist/index.html || (echo "index.html falta" && exit 3)
      - name: Zip artifact
        run: cd dist && zip -rq ../web-artifact.zip .
      - name: Deploy to Azure (publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: apps/web/web-artifact.zip
    env:
      AZURE_APP_NAME: "econeura-web-dev"
