name: Deploy WEB to Azure
on:
  push:
    branches: ["main", "fix/**", "release/**", "fix/azure-ci-20251006171711"]
  workflow_dispatch: {}
env:
  AZURE_APP_NAME: "econeura-web-dev"
  VITE_AI_ENDPOINT: "https://econeura-api-dev.azurewebsites.net/api/ai"
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm install || npm ci
      - name: Fail early if publish profile missing
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}" ]; then echo "Missing secret: AZURE_WEBAPP_PUBLISH_PROFILE_WEB"; exit 2; fi

      - run: VITE_AI_ENDPOINT="${{ env.VITE_AI_ENDPOINT }}" pnpm run build || VITE_AI_ENDPOINT="${{ env.VITE_AI_ENDPOINT }}" npm run build
      - name: Copy server.js into dist
        run: |
          if [ ! -f server.js ]; then echo "server.js missing"; exit 2; fi
          node -e "require('fs').cpSync('server.js','dist/server.js')"
      - name: Sanity dist
        run: |
          if [ ! -f dist/index.html ] || [ ! -f dist/server.js ]; then echo "dist incomplete"; ls -la dist || true; exit 2; fi
      - run: cd dist && zip -r ../web-artifact.zip .
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: web-artifact.zip
