name: Deploy API to Azure App Service
on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "apps/api_py/**"
      - ".github/workflows/deploy-api.yml"
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api_py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found - using stdlib only API"
          fi
      - name: Validate Python API
        run: |
          test -f server.py || { echo "ERROR: falta server.py"; exit 6; }
          python -c "import server; print('✅ API Python syntax OK')"
          echo "✅ API Python detectada correctamente"
      - name: Create Azure startup script
        run: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          cd /home/site/wwwroot
          export PYTHONPATH=/home/site/wwwroot
          python server.py
          EOF
          chmod +x startup.sh
          echo "✅ Script de startup creado"
      - name: Zip artifact
        run: zip -rq ../api-artifact.zip .
      - name: Deploy to Azure (publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: apps/api-artifact.zip
    env:
      AZURE_APP_NAME: "econeura-api-dev"
