name: Deploy WEB to Azure
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
env:
  AZURE_APP_NAME: "econeura-web-dev"
  BUILD_DIR: "apps/web/dist"
jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - name: Install deps
        run: |
          if [ -f pnpm-lock.yaml ]; then corepack enable; corepack prepare pnpm@8.15.5 --activate; pnpm -v; pnpm -r i --frozen-lockfile || pnpm -r i
          elif [ -f package-lock.json ]; then npm ci
          else npm i; fi
      - name: Build web
        run: |
          if [ -d apps/web ]; then (cd apps/web && (pnpm build || npm run build)); else echo "ERROR: apps/web no existe" && exit 2; fi
      - name: Validate build artifacts
        run: |
          test -d "$BUILD_DIR" || { echo "ERROR: no existe $BUILD_DIR"; exit 3; }
          test -f "$BUILD_DIR/index.html" || { echo "ERROR: falta index.html en $BUILD_DIR"; exit 4; }
          # Validate that it's a React SPA build
          grep -q "react" "$BUILD_DIR/index.html" && echo "✅ React build detected" || echo "WARN: No React detected in build"
          if [ -f apps/web/server.js ]; then cp apps/web/server.js "$BUILD_DIR/server.js" && echo "✅ server.js copied"; fi
      - name: Pre-deployment health check
        run: |
          # Check for common issues
          if [ -f "$BUILD_DIR/index.html" ]; then
            # Check file size (should be reasonable)
            size=$(stat -f%z "$BUILD_DIR/index.html" 2>/dev/null || stat -c%s "$BUILD_DIR/index.html" 2>/dev/null || echo "0")
            if [ "$size" -gt 1000000 ]; then echo "WARN: index.html muy grande ($size bytes)"; fi
            # Check for environment variables that might be exposed
            grep -i "secret\|password\|key" "$BUILD_DIR/index.html" && echo "WARN: Posibles secrets expuestos en build" || true
          fi
      - name: Zip artifact
        run: |
          cd "$BUILD_DIR"
          zip -r ../../web-artifact.zip .
          cd - >/dev/null
          ls -la apps/web-artifact.zip 2>/dev/null || true
      - name: Deploy to Azure (publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: apps/web-artifact.zip
