name: Dispatch CI Web Build via PAT and collect artifacts

on:
  workflow_dispatch: {}
  push:
    branches: ["fix/**", "main"]

jobs:
  dispatch-and-collect:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ci-web-build.yml via PAT
        env:
          PAT: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          START_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "Dispatching ci-web-build.yml at $START_TS"
          API="https://api.github.com/repos/$REPO/actions/workflows/ci-web-build.yml/dispatches"
          PAYLOAD=$(jq -n '{ref: "fix/azure-ci-20251006171711"}')
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$API" -H "Authorization: Bearer $PAT" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" -d "$PAYLOAD")
          echo "Dispatch HTTP status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" -ne 204 ]; then echo "Dispatch failed"; exit 2; fi
          echo "Dispatch accepted"

      - name: Wait for ci-web-build run
        env:
          PAT: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
          REPO: ${{ github.repository }}
          START_TS: ${{ github.event.head_commit.timestamp || '' }}
        run: |
          set -euo pipefail
          # find run created after START_TS
          RUN_ID=""
          for i in {1..60}; do
            sleep 5
            RUN_ID=$(curl -sS -H "Authorization: Bearer $PAT" "https://api.github.com/repos/$REPO/actions/workflows/ci-web-build.yml/runs?per_page=20" | jq -r ".workflow_runs[] | select(.created_at >= \"$START_TS\") | .id" | head -n1 || true)
            if [ -n "$RUN_ID" ]; then echo "Found run: $RUN_ID"; break; fi
          done
          if [ -z "$RUN_ID" ]; then echo "No run found"; exit 3; fi
          echo "Monitoring run $RUN_ID..."
          while true; do
            sleep 8
            STATUS=$(curl -sS -H "Authorization: Bearer $PAT" "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" | jq -r ".status")
            CONCL=$(curl -sS -H "Authorization: Bearer $PAT" "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" | jq -r ".conclusion")
            echo "status=$STATUS conclusion=$CONCL"
            if [ "$STATUS" = "completed" ]; then echo "Run completed: $CONCL"; break; fi
          done
          echo "$RUN_ID" > run_id.txt

      - name: Download artifacts from ci-web-build run
        env:
          PAT: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          RUN_ID=$(cat run_id.txt)
          echo "Listing artifacts for run $RUN_ID"
          ART_API="https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts"
          curl -sS -H "Authorization: Bearer $PAT" "$ART_API" -o /tmp/artifacts.json
          jq -r '.artifacts[] | .archive_download_url' /tmp/artifacts.json > /tmp/urls.txt || true
          mkdir -p /tmp/ci-artifacts
          n=0
          while read -r url; do
            n=$((n+1))
            echo "Downloading $url"
            curl -L -sS -H "Authorization: Bearer $PAT" -o /tmp/artifacts_$n.zip "$url"
            unzip -o /tmp/artifacts_$n.zip -d /tmp/ci-artifacts_$n || true
          done < /tmp/urls.txt || true

      - name: Upload collected artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-web-build-collected
          path: |
            /tmp/ci-artifacts_*/

      - name: Done
        run: echo "ci-web-build dispatched and artifacts collected as 'ci-web-build-collected'"
