name: Final full Fase D→E→F

# Trigger test

on:
  push:
    branches: [fix/azure-ci-20251006171711]

permissions:
  contents: read
  issues: write
  actions: read
  secrets: write
  id-token: write

jobs:
  full-flow:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SUBSCRIPTION_ID: 'fc22ced4-6dc1-4f52-aac1-170a62f98c57'
      RG: 'appsvc_linux_northeurope_basic'
      LOCATION: 'northeurope'
      PLAN: 'appsvc_linux_northeurope_basic'
      WEBAPP: 'econeura-web-dev'
      APIAPP: 'econeura-api-dev'
      NODE_FX: 'NODE|20-lts'
      PORT: '3000'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug env
        run: |
          echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID"
          echo "RG=$RG"
          echo "WEBAPP=$WEBAPP"
          echo "APIAPP=$APIAPP"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure login
        run: az account show --output table

      - name: Provision resources (Fase D)
        run: |
          echo "Starting Fase D: Provision"
          set -euo pipefail
          az account set --subscription "$SUBSCRIPTION_ID" || (echo "Failed to set subscription, continuing"; true)
          az group create -n "$RG" -l "$LOCATION" --output table || echo "RG creation failed, may already exist"
          if ! az appservice plan show -g "$RG" -n "$PLAN" --output table >/dev/null 2>&1; then
            az appservice plan create -g "$RG" -n "$PLAN" --sku B1 --is-linux --output table || echo "Plan creation failed"
          fi
          if ! az webapp show -g "$RG" -n "$WEBAPP" -o json >/dev/null 2>&1; then
            az webapp create -g "$RG" -p "$PLAN" -n "$WEBAPP" --runtime "$NODE_FX" -o table || echo "Webapp creation failed"
          fi
          if ! az webapp show -g "$RG" -n "$APIAPP" -o json >/dev/null 2>&1; then
            az webapp create -g "$RG" -p "$PLAN" -n "$APIAPP" --runtime "$NODE_FX" -o table || echo "API app creation failed"
          fi
          az webapp config set -g "$RG" -n "$WEBAPP" --always-on true -o table || echo "Webapp config failed"
          az webapp config set -g "$RG" -n "$WEBAPP" --set siteConfig.linuxFxVersion="$NODE_FX" -o table || echo "Webapp fx version failed"
          az webapp config appsettings set -g "$RG" -n "$WEBAPP" --settings WEBSITE_NODE_DEFAULT_VERSION="20-lts" WEBSITES_PORT="$PORT" VITE_AI_ENDPOINT="https://$APIAPP.azurewebsites.net/api/ai" -o table || echo "Webapp settings failed"
          az webapp config set -g "$RG" -n "$APIAPP" --always-on true -o table || echo "API config failed"
          az webapp config set -g "$RG" -n "$APIAPP" --set siteConfig.linuxFxVersion="$NODE_FX" -o table || echo "API fx version failed"
          az webapp config appsettings set -g "$RG" -n "$APIAPP" --settings WEBSITE_NODE_DEFAULT_VERSION="20-lts" WEBSITES_PORT="$PORT" ALLOWED_ORIGIN="https://$WEBAPP.azurewebsites.net,http://localhost:5173" -o table || echo "API settings failed"

      - name: Download publish-profiles (Fase E)
        run: |
          echo "Starting Fase E: Download profiles"
          set -euo pipefail
          az webapp deployment list-publishing-profiles -g "$RG" -n "$WEBAPP" --output xml > publish_profile_web.xml || (echo "Failed to download web profile"; exit 1)
          az webapp deployment list-publishing-profiles -g "$RG" -n "$APIAPP" --output xml > publish_profile_api.xml || (echo "Failed to download api profile"; exit 1)
          ls -la *.xml

      - name: Read profiles for secrets
        run: |
          set -euo pipefail
          WEB_PROFILE=$(cat publish_profile_web.xml)
          API_PROFILE=$(cat publish_profile_api.xml)
          echo "WEB_PROFILE<<EOF" >> $GITHUB_ENV
          echo "$WEB_PROFILE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "API_PROFILE<<EOF" >> $GITHUB_ENV
          echo "$API_PROFILE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Create secrets (Fase E)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh secret set AZURE_WEBAPP_PUBLISH_PROFILE_WEB --body "${{ env.WEB_PROFILE }}"

      - name: Create secrets API (Fase E)
        run: |
          gh secret set AZURE_WEBAPP_PUBLISH_PROFILE_API --body "${{ env.API_PROFILE }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Build Web (Fase F)
        working-directory: apps/web
        run: |
          echo "Starting Fase F: Build Web"
          set -euo pipefail
          pnpm install || npm ci || (echo "build dependencies failed"; exit 1)
          VITE_AI_ENDPOINT="https://$APIAPP.azurewebsites.net/api/ai" pnpm run build || npm run build || (echo "build failed"; exit 1)
          if [ ! -f server.js ]; then echo "server.js missing"; exit 2; fi
          cd dist && zip -r ../web-artifact.zip . || (echo "zip failed"; exit 1)

      - name: Deploy Web (Fase F)
        run: |
          echo "Starting Deploy Web"
          set -euo pipefail
          WEB_ZIP=apps/web/web-artifact.zip
          az webapp deploy --resource-group "$RG" --name "$WEBAPP" --src-path "$WEB_ZIP" || az webapp deployment source config-zip -g "$RG" -n "$WEBAPP" --src "$WEB_ZIP" || (echo "Deploy web failed"; exit 1)

      - name: Build API (Fase F)
        working-directory: services/api
        run: |
          set -euo pipefail
          pnpm install || npm ci || echo "build dependencies skipped for api"
          zip -r ../api-artifact.zip . || (echo "zip api failed"; exit 1)

      - name: Deploy API (Fase F)
        run: |
          set -euo pipefail
          API_ZIP=services/api/../api-artifact.zip
          az webapp deploy --resource-group "$RG" --name "$APIAPP" --src-path "$API_ZIP" || az webapp deployment source config-zip -g "$RG" -n "$APIAPP" --src "$API_ZIP" || (echo "Deploy api failed"; exit 1)

      - name: Smoke tests (Fase F)
        run: |
          echo "Starting Smoke Tests"
          set -euo pipefail
          WEB_HOST="$WEBAPP.azurewebsites.net"
          API_HOST="$APIAPP.azurewebsites.net"
          echo "Checking API health: https://$API_HOST/api/ai/health"
          for i in {1..10}; do
            if curl -fsS --max-time 30 https://$API_HOST/api/ai/health -o /tmp/api-health.json; then
              echo "API health OK"
              break
            else
              echo "API health attempt $i failed, retrying in 30s..."
              sleep 30
            fi
          done
          if [ ! -f /tmp/api-health.json ]; then echo "API health failed after retries"; exit 2; fi
          echo "Checking Web root: https://$WEB_HOST"
          for i in {1..5}; do
            if curl -fsSI --max-time 30 https://$WEB_HOST | head -n 5; then
              echo "Web check OK"
              break
            else
              echo "Web check attempt $i failed, retrying in 30s..."
              sleep 30
            fi
          done
          echo "Smoke checks passed"

      - name: Report completion
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          BODY="Fase D→E→F completada automáticamente.

          - Provision: RG=$RG, web=$WEBAPP, api=$APIAPP
          - Secrets: AZURE_WEBAPP_PUBLISH_PROFILE_WEB y AZURE_WEBAPP_PUBLISH_PROFILE_API creados
          - Deploy: web y api desplegados
          - Smoke: PASS

          Revisa Actions logs para detalles."
          API="https://api.github.com/repos/$REPO/issues"
          PAYLOAD=$(jq -nc --arg title "[Final] Fase D→E→F summary" --arg body "$BODY" '{title:$title, body:$body}')
          curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" -d "$PAYLOAD" "$API" > /tmp/issue.json || true
          jq -r '.html_url' /tmp/issue.json || true