name: Provision postprocess (Fase E)

on:
  workflow_run:
    workflows: ["Azure provision (Fase D)"]
    types: [completed]

permissions:
  contents: read
  actions: read
  secrets: write

jobs:
  publish-profiles-to-secrets:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download publish-profiles artifact from provision run
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          echo "Listing artifacts for run $RUN_ID"
          ARTIFACTS_API="https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts"
          curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$ARTIFACTS_API" > /tmp/artifacts.json
          jq -r '.artifacts[] | select(.name=="publish-profiles") | .archive_download_url' /tmp/artifacts.json > /tmp/publish_url.txt
          P_URL=$(cat /tmp/publish_url.txt || true)
          if [ -z "$P_URL" ]; then echo "publish-profiles artifact not found"; exit 2; fi
          echo "Downloading artifact from $P_URL"
          curl -L -sS -H "Authorization: Bearer $GITHUB_TOKEN" -o /tmp/publish_profiles.zip "$P_URL"
          unzip -o /tmp/publish_profiles.zip -d /tmp/publish_profiles
          ls -la /tmp/publish_profiles || true

      - name: Load publish profiles into env
        run: |
          set -euo pipefail
          if [ -f /tmp/publish_profiles/publish_profile_web.xml ]; then
            echo "WEB_PROFILE<<'EOF'" >> $GITHUB_ENV
            cat /tmp/publish_profiles/publish_profile_web.xml >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "publish_profile_web.xml not found"; exit 2
          fi
          if [ -f /tmp/publish_profiles/publish_profile_api.xml ]; then
            echo "API_PROFILE<<'EOF'" >> $GITHUB_ENV
            cat /tmp/publish_profiles/publish_profile_api.xml >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "publish_profile_api.xml not found"; exit 2
          fi

      - name: Create/update secret: AZURE_WEBAPP_PUBLISH_PROFILE_WEB
        uses: peter-evans/create-or-update-secret@v2
        with:
          secret-name: AZURE_WEBAPP_PUBLISH_PROFILE_WEB
          secret-value: ${{ env.WEB_PROFILE }}

      - name: Create/update secret: AZURE_WEBAPP_PUBLISH_PROFILE_API
        uses: peter-evans/create-or-update-secret@v2
        with:
          secret-name: AZURE_WEBAPP_PUBLISH_PROFILE_API
          secret-value: ${{ env.API_PROFILE }}

      - name: Done
        run: echo "Publish-profiles saved as repo secrets: AZURE_WEBAPP_PUBLISH_PROFILE_WEB, AZURE_WEBAPP_PUBLISH_PROFILE_API"
