name: Report Fase E (verify publish-profile secrets)

on:
  push:
    branches: [ "fix/azure-ci-20251006171711" ]

permissions:
  contents: read
  issues: write
  actions: read
  secrets: read

jobs:
  check-secrets-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Wait a bit for postprocess to run
        run: |
          echo "Sleeping 30s to allow Fase E postprocess to complete..."
          sleep 30

      - name: Check for publish-profile secrets via API
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          API="https://api.github.com/repos/$REPO/actions/secrets"
          echo "Listing repo secrets..."
          curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$API" > /tmp/secrets.json
          jq -r '.secrets[]?.name' /tmp/secrets.json || true
          WEB_EXISTS=$(jq -r '.secrets[]?.name == "AZURE_WEBAPP_PUBLISH_PROFILE_WEB" | select(.==true) | . // empty' /tmp/secrets.json || true)
          API_EXISTS=$(jq -r '.secrets[]?.name == "AZURE_WEBAPP_PUBLISH_PROFILE_API" | select(.==true) | . // empty' /tmp/secrets.json || true)
          # simpler detection
          WEB_PRESENT=$(jq -r '[.secrets[]?.name] | index("AZURE_WEBAPP_PUBLISH_PROFILE_WEB") != null' /tmp/secrets.json || echo false)
          API_PRESENT=$(jq -r '[.secrets[]?.name] | index("AZURE_WEBAPP_PUBLISH_PROFILE_API") != null' /tmp/secrets.json || echo false)
          echo "WEB_PRESENT=$WEB_PRESENT API_PRESENT=$API_PRESENT"
          if [ "$WEB_PRESENT" = "true" ] && [ "$API_PRESENT" = "true" ]; then
            BODY="Fase E completada: secretos AZURE_WEBAPP_PUBLISH_PROFILE_WEB y AZURE_WEBAPP_PUBLISH_PROFILE_API detectados."
            echo "Secrets present"
            ISSUE_API="https://api.github.com/repos/$REPO/issues"
            curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" -d "{\"title\": \"[Fase E] publish-profiles -> secrets (automated)\", \"body\": \"$BODY\" }" "$ISSUE_API" > /tmp/issue.json
            jq -r '.html_url' /tmp/issue.json || true
          else
            echo "Fase E no completada aún. WEB_PRESENT=$WEB_PRESENT API_PRESENT=$API_PRESENT"
            exit 2
          fi
