name: Smoke tests after Deploy

on:
  workflow_run:
    workflows: ["Deploy WEB to Azure"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run smoke checks for Web and API
        run: |
          set -euo pipefail
          WEB_HOST="econeura-web-dev.azurewebsites.net"
          API_HOST="econeura-api-dev.azurewebsites.net"

          echo "Checking API health: https://$API_HOST/api/ai/health"
          curl -fsS https://$API_HOST/api/ai/health -o /tmp/api-health.json || (
            echo "API health check failed";
            echo "--- API response (if any) ---";
            cat /tmp/api-health.json || true;
            exit 2
          )

          echo "Checking Web root: https://$WEB_HOST"
          curl -fsSI https://$WEB_HOST | head -n 5 || (
            echo "Web root check failed"; exit 3
          )

          echo "Smoke checks passed"
