name: Test Workflow Trigger

on:
  push:
    branches: [fix/azure-ci-20251006171711]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Workflow trigger works! All workflows should be green if this passes."